from .regularization import compute_kan_regularization
from .plotting import (
    plot_trajectory_comparison,
    plot_phase_space,
    plot_phase_portrait_with_streamlines,
    plot_3d_lorenz_trajectory,
    plot_pendulum_phase_and_energy,
    plot_loss_curves,
    plot_model_comparison_curves,
    plot_gradient_norm_dynamics,
    plot_benchmark_comparison,
)
from .metrics import (
    compute_mse,
    compute_rmse,
    compute_mae,
    compute_r2_score,
    compute_relative_l2_error,
    count_parameters,
    compute_gradient_norm,
    estimate_lipschitz_bound,
    compute_energy_violation,
    track_nfe,
)

__all__ = [
    "compute_kan_regularization",
    "plot_trajectory_comparison",
    "plot_phase_space",
    "plot_phase_portrait_with_streamlines",
    "plot_3d_lorenz_trajectory",
    "plot_pendulum_phase_and_energy",
    "plot_loss_curves",
    "plot_model_comparison_curves",
    "plot_gradient_norm_dynamics",
    "plot_benchmark_comparison",
    "compute_mse",
    "compute_rmse",
    "compute_mae",
    "compute_r2_score",
    "compute_relative_l2_error",
    "count_parameters",
    "compute_gradient_norm",
    "estimate_lipschitz_bound",
    "compute_energy_violation",
    "track_nfe",
]
