"""
Every results table whose entries come straight from the runs' metrics.json.

Nothing is recomputed here: each cell is a field that implementation/train.py
wrote at the end of training. Field names used:
    best.train_mse, best.extrap_mse, best.extrap_r2, best.extrap_rel_l2,
    estimated_lipschitz_bound, training_time_seconds, seconds_per_epoch,
    nfe_per_epoch_train, config.n_train_points,
    stability.clip_engaged_fraction, stability.grad_norm_median_preclip

Tables (label in report -> section):
    tab:solver-ablation  (Sec. 3.2; last column from s03_work_precision.py)
    tab:basis-ablation   (Sec. 3.3; kappa_2 column from s05_basis_catalog.py)
    tab:noise-dt         (Sec. 3.4)
    tab:kan-vs-mlp       (Sec. 2.4; top block; bottom block from s06/s09)
    tab:cost             (Sec. 2.3)
    tab:phase4           (Sec. 9)

Output: figures/analysis/tables.md   (the tables, formatted as in the report)
        numbers.json -> tables
"""

import json

from common import (B, BASES, BASIS_LABEL, OUT, P4, ROOT, SOLVER_LABEL, SOLVERS, metrics,
                    save_numbers)


def sci(x, d=2):
    return f"{x:.{d}e}"


def row(key_or_path):
    m = metrics(key_or_path) if isinstance(key_or_path, str) else \
        json.loads((key_or_path / "metrics.json").read_text())
    b, st = m["best"], m.get("stability", {})
    return dict(epochs=m["config"]["num_epochs"], n_train=m["config"]["n_train_points"],
                params=m["config"]["parameters"],
                train_mse=b["train_mse"], extrap_mse=b["extrap_mse"], extrap_r2=b["extrap_r2"],
                rel_l2=b["extrap_rel_l2"], lipschitz=m["estimated_lipschitz_bound"],
                wall_s=m["training_time_seconds"], s_per_epoch=m["seconds_per_epoch"],
                nfe_per_epoch=m.get("nfe_per_epoch_train"),
                clip=st.get("clip_engaged_fraction"), grad_med=st.get("grad_norm_median_preclip"))


def md_table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(lines)


def main():
    T, md = {}, ["# Tables regenerated from metrics.json", "",
                 "Generated by `report/reproduce/s01_tables.py`. Values are rounded as in the report.", ""]

    # --- solver ablation
    T["solver_ablation"] = {s: row(f"solver_{s}") for s in SOLVERS}
    md += ["## tab:solver-ablation (RBF basis, h = 0.05, 10k epochs)", "", md_table(
        ["Solver", "NFE/epoch", "Train MSE", "Extrap MSE", "Extrap R2", "Lipschitz", "Wall-clock (s)"],
        [[SOLVER_LABEL[s], r["nfe_per_epoch"], sci(r["train_mse"]), sci(r["extrap_mse"]),
          f"{r['extrap_r2']:.5f}", f"{r['lipschitz']:.2f}", f"{r['wall_s']:.0f}"]
         for s, r in T["solver_ablation"].items()]), ""]

    # --- basis ablation
    T["basis_ablation"] = {b: row(f"basis_{b}") for b in BASES}
    md += ["## tab:basis-ablation (Tsit5, G = 5, 10k epochs)", "", md_table(
        ["Basis", "Train MSE", "Extrap MSE", "R2", "Rel L2", "Lipschitz", "Wall-clock (s)"],
        [[BASIS_LABEL[b], sci(r["train_mse"]), sci(r["extrap_mse"]), f"{r['extrap_r2']:.5f}",
          f"{100 * r['rel_l2']:.2f}%", f"{r['lipschitz']:.2f}", f"{r['wall_s']:.0f}"]
         for b, r in T["basis_ablation"].items()]), ""]

    # --- step size and noise
    keys = [("dt_0.05", "dt = 0.05"), ("dt_0.1", "dt = 0.1 (reference)"), ("dt_0.2", "dt = 0.2"),
            ("noise_0.01", "sigma = 0.01"), ("noise_0.05", "sigma = 0.05"), ("noise_0.1", "sigma = 0.1")]
    T["noise_dt"] = {k: row(k) for k, _ in keys}
    md += ["## tab:noise-dt (Tsit5, RBF, 10k epochs)", "", md_table(
        ["Configuration", "Train points", "Train MSE", "Extrap MSE", "Extrap R2", "Lipschitz", "Wall-clock (s)"],
        [[lab, T["noise_dt"][k]["n_train"], sci(T["noise_dt"][k]["train_mse"]), sci(T["noise_dt"][k]["extrap_mse"]),
          f"{T['noise_dt'][k]['extrap_r2']:.5f}", f"{T['noise_dt'][k]['lipschitz']:.2f}",
          f"{T['noise_dt'][k]['wall_s']:.0f}"] for k, lab in keys]), ""]

    # --- KAN vs MLP (top block)
    kvm = [("KAN-ODE (RBF)", B / "kanode_flagship"), ("MLP-ODE (SiLU)", B / "mlpode_baseline_silu"),
           ("MLP-ODE (tanh, paper)", B / "mlpode_baseline")]
    T["kan_vs_mlp"] = {lab: row(p) for lab, p in kvm}
    md += ["## tab:kan-vs-mlp, top block (10k epochs)", "",
           "Epoch milestones are in numbers.json -> epochs_to_train_mse (s11); field error, period and "
           "H drift in field_error / equilibria (s06, s09).", "", md_table(
            ["Model", "Params", "Train MSE", "Extrap MSE", "Extrap R2", "Rel L2", "Lipschitz", "Wall-clock (s)"],
            [[lab, r["params"], sci(r["train_mse"]), sci(r["extrap_mse"]), f"{r['extrap_r2']:.5f}",
              f"{100 * r['rel_l2']:.2f}%", f"{r['lipschitz']:.2f}", f"{r['wall_s']:.0f}"]
             for lab, r in T["kan_vs_mlp"].items()]), ""]

    # --- per-epoch cost, local against cloud
    cost = [("Euler / RBF", B / "ablation_solvers" / "solver_euler", P4 / "euler_50k"),
            ("Tsit5 / RBF (reference)", B / "kanode_flagship", P4 / "tsit5_rbf_50k"),
            ("Tsit5 / B-spline", B / "ablation_activations" / "basis_bspline", P4 / "bspline_25k"),
            ("MLP-ODE, SiLU", B / "mlpode_baseline_silu", P4 / "mlp_silu_50k"),
            ("MLP-ODE, tanh", B / "mlpode_baseline", P4 / "mlp_paperspec_50k")]
    T["cost"] = {}
    rows = []
    for lab, loc, cloud in cost:
        a, c = row(loc)["s_per_epoch"], row(cloud)["s_per_epoch"]
        T["cost"][lab] = dict(local_s_per_epoch=a, cloud_s_per_epoch=c, ratio=c / a,
                              h_1e5_local=a * 1e5 / 3600, h_1e5_cloud=c * 1e5 / 3600)
        rows.append([lab, f"{a:.4f}", f"{c:.4f}", f"{c / a:.2f}x", f"{a * 1e5 / 3600:.1f} h", f"{c * 1e5 / 3600:.1f} h"])
    lv = [p.parent for p in B.rglob("metrics.json")
          if json.loads(p.read_text())["config"]["dataset"] == "lotka_volterra"]
    cpu_h = sum(json.loads((p / "metrics.json").read_text())["training_time_seconds"] for p in lv) / 3600
    ref_ratio = T["cost"]["Tsit5 / RBF (reference)"]["ratio"]
    T["cost"]["all_lv"] = dict(n_configs=len(lv), cpu_h_1e4=cpu_h, cpu_h_1e5_local=10 * cpu_h,
                               cpu_h_1e5_cloud_at_reference_ratio=10 * cpu_h * ref_ratio)
    rows.append([f"All {len(lv)} Lotka-Volterra configurations", f"{cpu_h:.1f} CPU-h at 1e4 epochs", "", "",
                 f"{10 * cpu_h:.0f} h", f"~{10 * cpu_h * ref_ratio:.0f} h"])
    md += ["## tab:cost (seconds per epoch, averaged over the full run)", "", md_table(
        ["Configuration", "Local s/epoch", "Cloud s/epoch", "Ratio", "1e5 epochs, local", "1e5 epochs, cloud"],
        rows), ""]

    # --- Phase 4: 10k against the extended budget
    p4 = [("Euler / RBF", "solver_euler", "euler_50k"), ("Tsit5 / RBF", "basis_rbf", "kan_50k"),
          ("Tsit5 / B-spline", "basis_bspline", "bspline_25k"), ("MLP-ODE, SiLU", "mlp_silu", "mlp_silu_50k"),
          ("MLP-ODE, tanh (paper)", "mlp_tanh", "mlp_tanh_50k")]
    T["phase4"] = {}
    rows = []
    for lab, short, long in p4:
        s, l = row(short), row(long)
        T["phase4"][lab] = {"10k": s, "extended": l}
        for r, tag in [(s, "10k"), (l, f"{l['epochs'] // 1000}k")]:
            clip = "" if tag == "10k" else f"{100 * r['clip']:.1f}%"
            gm = "" if tag == "10k" else f"{r['grad_med']:.3f}"
            rows.append([lab if tag == "10k" else "", tag, sci(r["train_mse"]), sci(r["extrap_mse"]),
                         f"{r['extrap_r2']:.6f}", f"{r['lipschitz']:.2f}", clip, gm])
    md += ["## tab:phase4 (10k against the extended budget)", "", md_table(
        ["Configuration", "Epochs", "Train MSE", "Extrap MSE", "Extrap R2", "Lipschitz", "Clip", "Median grad"],
        rows), ""]

    (OUT / "tables.md").write_text("\n".join(md), encoding="utf-8")
    print(f"  wrote {(OUT / 'tables.md').relative_to(ROOT)}")
    save_numbers(dict(tables=T))


if __name__ == "__main__":
    main()
